name: Release

on:
  push:
    tags:
      - '*'

env:
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Setup `Node.js`
      uses: actions/setup-node@v2.5.0
      with:
        node-version: 16
        
    - name: Set up `Tag`
      id: ghtag
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

    - name: Instal deps
      run: yarn

    - name: Build `SMUI`
      env:
        TAG: ${{ steps.ghtag.outputs.tag }}
      run: |
        yarn build
        mv dist ui
        echo $TAG >> ui/tag.txt

    - name: Zip it
      run: zip -9 -r smui.zip ui

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: smui.zip
